Repository prgrms-be-devcourse/NBE6-8-2-Team08, pull requests merged in 2025-07, with the labels that each got.

#18 [BE] feat: application.yml 설정
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: enhancement

#37 [BE] Project 생성 API 추가
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectDetailResponse.java
  backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
  backend/src/main/java/com/devmatch/backend/domain/project/entity/ProjectStatus.java
  backend/src/main/java/com/devmatch/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/devmatch/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/devmatch/backend/exception/GlobalExceptionHandler.java
Labels: enhancement

#69 [BE] feat: 역할 배분 내용 수정 API 구현
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
Labels: enhancement

#71 [BE] feat: 프로젝트 삭제 API 구현
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
Labels: enhancement

#73 [BE] feat: 지원서 작성, 지원서 전체 조회 로직 구현
  backend/src/main/java/com/devmatch/backend/domain/application/dto/ApplicationDto.java
  backend/src/main/java/com/devmatch/backend/domain/application/dto/request/ApplicationCreateRequestDto.java
  backend/src/main/java/com/devmatch/backend/domain/application/entity/Application.java
  backend/src/main/java/com/devmatch/backend/domain/application/service/ApplicationService.java
Labels: enhancement

#86 [BE] feat: 프로젝트 지원서 작성 API 구현
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
Labels: enhancement

#93 [BE] fix: ApplicationController id 매핑 문제, ApplicationRepository 타입 오류 수정
  backend/src/main/java/com/devmatch/backend/domain/analysis/service/AnalysisService.java
  backend/src/main/java/com/devmatch/backend/domain/application/controller/ApplicationController.java
  backend/src/main/java/com/devmatch/backend/domain/application/repository/ApplicationRepository.java
Labels: maintenance

#103 [BE] 프로젝트 삭제에 대한 연간관계 추가 및 유효성 검사 강화
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectApplyRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectContentUpdateRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectStatusUpdateRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/devmatch/backend/exception/SameStatusException.java
Labels: enhancement, maintenance

#102 [BE] fix: Application 테스트 중 발생한 이슈 수정, 테스트를 위한 csrf 권한 해제
  backend/src/main/java/com/devmatch/backend/domain/application/controller/ApplicationController.java
  backend/src/main/java/com/devmatch/backend/domain/application/dto/request/ApplicationStatusUpdateRequestDto.java
  backend/src/main/java/com/devmatch/backend/domain/application/entity/Application.java
  backend/src/main/java/com/devmatch/backend/domain/application/enums/ApplicationStatus.java
  backend/src/main/java/com/devmatch/backend/domain/application/repository/ApplicationRepository.java
  backend/src/main/java/com/devmatch/backend/domain/application/service/ApplicationService.java
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/security/SecurityConfig.java
Labels: maintenance

#118 [BE] 개발용 DBMS 수정 및 미흡한 조건 검사 수정
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
  backend/src/main/resources/application-dev.yml
Labels: maintenance

#129 [BE] 사용자를 인증 객체를 활용하는 방식으로 수정
  backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectApplyRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
  backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectDetailResponse.java
  backend/src/main/java/com/devmatch/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
Labels: maintenance
